import {Router}from "express";
import { validateMovie } from "../validators/movieValidator";
import { GetAllMovies,GetOneMovie,CreateMovie,UpdateMovie,DeleteMovie } from "../controllers/movieController";
const router=Router();
router.post("/movies",validateMovie,CreateMovie);
router.put("/movies/:id",validateMovie,UpdateMovie);
router.get("/movies",GetAllMovies);
router.get("/movie/:id",GetOneMovie);
router.delete("/movies/:id",DeleteMovie);
export default router;